---
title: "The Problem of Differential Ranking (DR)"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
```

# 1. Synthetic data

```{r, message=FALSE, warning=FALSE, comment=NA}
n_taxa = 10
n_sample = 100

set.seed(100)
alpha0 = sample(c(log(50), log(200), log(10000)),
                n_taxa, replace = TRUE, 
                prob = c(0.6, 0.3, 0.1)) 

alpha1 = rnorm(n_taxa, mean = 0, sd = 3)
alpha2 = rnorm(n_taxa, mean = 0, sd = 2)

meta_data = data.frame(x1 = rep(c(0, 1), each = n_sample/2),
                       x2 = runif(n_sample, 10, 20))

# Case 1: only 1 covariate
A = matrix(NA, nrow = n_taxa, ncol = n_sample)

for (i in 1:n_taxa) {
  A[i, ] = alpha0[i] + alpha1[i] * meta_data$x1 
}

A_alr = t(t(A) - A[n_taxa, ])
A_alr = A_alr[-n_taxa, ]

beta1_1 = apply(A_alr, 1, function(x) coef(lm(x ~ meta_data$x1))[2])

# Case 2: has two covariates
A = matrix(NA, nrow = n_taxa, ncol = n_sample)

for (i in 1:n_taxa) {
  A[i, ] = alpha0[i] + alpha1[i] * meta_data$x1 + alpha2[i] * meta_data$x2
}

A_alr = t(t(A) - A[n_taxa, ])
A_alr = A_alr[-n_taxa, ]

beta1_2 = apply(A_alr, 1, function(x) coef(lm(x ~ meta_data$x1 + meta_data$x2))[2])
```

# 2. Plotting

```{r, message=FALSE, warning=FALSE, comment=NA}
dat_fig = data.frame(sample_id = factor(1:9), 
                     alpha1 = rank(alpha1[-n_taxa]),
                     beta1_1 = rank(beta1_1),
                     beta1_2 = rank(beta1_2))
dat_fig_long = dat_fig %>% gather(key = "beta1", value = "value", beta1_1:beta1_2)

p = dat_fig_long %>% ggplot(aes(x = alpha1, y = value)) + 
  geom_point(aes(color = sample_id)) +
  labs(x = "Alpha1", y = "Beta1") +
  facet_grid(.~beta1) + 
  scale_color_discrete(name = "Sample") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") +
  theme_bw()

p
```

# Session information

```{r, message=FALSE, warning=FALSE, comment=NA}
sessionInfo()
devtools::session_info()
```
